version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api_test
      MYSQL_PASSWORD: root
    expose:
      - '3306'    
volumes:
  db:
